name: auto-assign-PR
on:
  pull_request:
    types: [opened, reopened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1.0.2
        with:
          reviewers: roninsharma25
